name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: 'yarn'
      - run: |
            cd backend
            yarn --frozen-lockfile
            yarn pack
            node 
            yarn add jest
            yarn testini
            #yarn test

